on: [push]

name: CI

jobs:
  build_and_test:
    name: many-rs build and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SoftHSMv2
        run: |
          sudo apt-get update -y -qq &&
          sudo apt-get install -y -qq libsofthsm2 &&
          mkdir /tmp/tokens
          echo "directories.tokendir = /tmp/tokens" > /tmp/softhsm2.conf
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Check lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release --all-targets --all-features -- -D warnings
      - name: Perform build (--release)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets --all-features
      - name: Run tests
        uses: actions-rs/cargo@v1
        env:
          PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
          SOFTHSM2_CONF: /tmp/softhsm2.conf
        with:
          command: test
          args: --all-targets --all-features

